(function() {function f(a){throw a;}var i=void 0,k=!0,m=null,n=!1;function aa(a){return function(){return this[a]}}function p(a){return function(){return a}}var r,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function s(a){return a!==i}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function t(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){var b=typeof a;return"object"==b&&a!=m||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){a||f(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){v=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return v.apply(m,arguments)}function ja(a,b){function c(){}c.prototype=b.prototype;a.wd=b.prototype;a.prototype=new c};function ka(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}f(Error("Invalid JSON string: "+a))}function la(){this.Nb=i}
function ma(a,b,c){switch(typeof b){case "string":na(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==m){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",g=0;g<d;g++)c.push(e),e=b[g],ma(a,a.Nb?a.Nb.call(b,String(g),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(e=b[g],"function"!=typeof e&&(c.push(d),
na(g,c),c.push(":"),ma(a,a.Nb?a.Nb.call(b,g,e):e,c),d=","));c.push("}");break;case "function":break;default:f(Error("Unknown type: "+typeof b))}}var oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function na(a,b){b.push('"',a.replace(pa,function(a){if(a in oa)return oa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return oa[a]=e+b.toString(16)}),'"')};function y(a){if("undefined"!==typeof JSON&&s(JSON.stringify))a=JSON.stringify(a);else{var b=[];ma(new la,a,b);a=b.join("")}return a};function qa(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,z(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&f(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function B(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:ra.assert(n,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function C(a,b,c,d){(!d||s(c))&&"function"!=da(c)&&f(Error(B(a,b,d)+"must be a valid function."))}function sa(a,b,c){s(c)&&(!ga(c)||c===m)&&f(Error(B(a,b,k)+"must be a valid context object."))};function D(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ta(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var ua={},ra={},va=/[\[\].#$\/]/,wa=/[\[\].#$]/;function xa(a){return t(a)&&0!==a.length&&!va.test(a)}function ya(a,b,c){(!c||s(b))&&za(B(a,1,c),b)}
function za(a,b,c,d){c||(c=0);d||(d=[]);s(b)||f(Error(a+"contains undefined"+Aa(d)));"function"==da(b)&&f(Error(a+"contains a function"+Aa(d)));Ba(b)&&f(Error(a+"contains "+b.toString()+Aa(d)));1E3<c&&f(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));t(b)&&(b.length>10485760/3&&10485760<ua.xd.vd(b).length)&&f(Error(a+"contains a string greater than 10485760 utf8 bytes"+Aa(d)+" ('"+b.substring(0,50)+"...')"));if(ga(b))for(var e in b)D(b,e)&&(".priority"!==e&&(".value"!==
e&&!xa(e))&&f(Error(a+"contains an invalid key ("+e+")"+Aa(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),za(a,b[e],c+1,d),d.pop())}function Aa(a){return 0==a.length?"":" in property "+a.join(".")}function Ca(a,b,c,d){(!d||s(c))&&(c!==m&&!fa(c)&&!t(c))&&f(Error(B(a,b,d)+"must be a valid firebase priority (null or a string.)"))}
function Da(a,b,c){if(!c||s(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:f(Error(B(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}function Ea(a,b){s(b)&&!xa(b)&&f(Error(B(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}
function Fa(a,b){(!t(b)||0===b.length||wa.test(b))&&f(Error(B(a,1,n)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function Ga(a,b){".info"===E(b)&&f(Error(a+" failed: Can't modify data under /.info/"))};function F(a,b,c,d,e,g,h){this.n=a;this.path=b;this.qa=c;this.W=d;this.ia=e;this.oa=g;this.La=h;s(this.W)&&(s(this.oa)&&s(this.qa))&&f("Query: Can't combine startAt(), endAt(), and limit().")}F.prototype.fc=function(a,b){A("Query.on",2,4,arguments.length);Da("Query.on",a,n);C("Query.on",2,b,n);var c=Ha("Query.on",arguments[2],arguments[3]);this.n.sb(this,a,b,c.cancel,c.S);return b};F.prototype.on=F.prototype.fc;
F.prototype.zb=function(a,b,c){A("Query.off",0,3,arguments.length);Da("Query.off",a,k);C("Query.off",2,b,k);sa("Query.off",3,c);this.n.Mb(this,a,b,c)};F.prototype.off=F.prototype.zb;F.prototype.jd=function(a,b){function c(h){g&&(g=n,e.zb(a,c),b.call(d.S,h))}A("Query.once",2,4,arguments.length);Da("Query.once",a,n);C("Query.once",2,b,n);var d=Ha("Query.once",arguments[2],arguments[3]),e=this,g=k;this.fc(a,c,function(){e.zb(a,c);d.cancel&&d.cancel.call(d.S)})};F.prototype.once=F.prototype.jd;
F.prototype.cd=function(a){A("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&f("Query.limit: First argument must be a positive integer.");return new F(this.n,this.path,a,this.W,this.ia,this.oa,this.La)};F.prototype.limit=F.prototype.cd;F.prototype.sd=function(a,b){A("Query.startAt",0,2,arguments.length);Ca("Query.startAt",1,a,k);Ea("Query.startAt",b);s(a)||(b=a=m);return new F(this.n,this.path,this.qa,a,b,this.oa,this.La)};F.prototype.startAt=F.prototype.sd;
F.prototype.Zc=function(a,b){A("Query.endAt",0,2,arguments.length);Ca("Query.endAt",1,a,k);Ea("Query.endAt",b);return new F(this.n,this.path,this.qa,this.W,this.ia,a,b)};F.prototype.endAt=F.prototype.Zc;function Ia(a){var b={};s(a.W)&&(b.sp=a.W);s(a.ia)&&(b.sn=a.ia);s(a.oa)&&(b.ep=a.oa);s(a.La)&&(b.en=a.La);s(a.qa)&&(b.l=a.qa);s(a.W)&&(s(a.ia)&&a.W===m&&a.ia===m)&&(b.vf="l");return b}F.prototype.Ca=function(){var a=Ja(Ia(this));return"{}"===a?"default":a};
function Ha(a,b,c){var d={};b&&c?(d.cancel=b,C(a,3,d.cancel,k),d.S=c,sa(a,4,d.S)):b&&("object"===typeof b&&b!==m?d.S=b:"function"===typeof b?d.cancel=b:f(Error(B(a,3,k)+"must either be a cancel callback or a context object.")));return d};function H(a){if(a instanceof H)return a;if(1==arguments.length){this.k=a.split("/");for(var b=0,c=0;c<this.k.length;c++)0<this.k[c].length&&(this.k[b]=this.k[c],b++);this.k.length=b;this.U=0}else this.k=arguments[0],this.U=arguments[1]}function E(a){return a.U>=a.k.length?m:a.k[a.U]}function Ka(a){var b=a.U;b<a.k.length&&b++;return new H(a.k,b)}function Na(a){return a.U<a.k.length?a.k[a.k.length-1]:m}r=H.prototype;
r.toString=function(){for(var a="",b=this.U;b<this.k.length;b++)""!==this.k[b]&&(a+="/"+this.k[b]);return a||"/"};r.parent=function(){if(this.U>=this.k.length)return m;for(var a=[],b=this.U;b<this.k.length-1;b++)a.push(this.k[b]);return new H(a,0)};r.A=function(a){for(var b=[],c=this.U;c<this.k.length;c++)b.push(this.k[c]);if(a instanceof H)for(c=a.U;c<a.k.length;c++)b.push(a.k[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new H(b,0)};
r.e=function(){return this.U>=this.k.length};function Oa(a,b){var c=E(a);if(c===m)return b;if(c===E(b))return Oa(Ka(a),Ka(b));f("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}r.contains=function(a){var b=0;if(this.k.length>a.k.length)return n;for(;b<this.k.length;){if(this.k[b]!==a.k[b])return n;++b}return k};function Pa(){this.children={};this.Zb=0;this.value=m}function Qa(a,b,c){this.wb=a?a:"";this.fb=b?b:m;this.m=c?c:new Pa}function J(a,b){for(var c=b instanceof H?b:new H(b),d=a,e;(e=E(c))!==m;)d=new Qa(e,d,ta(d.m.children,e)||new Pa),c=Ka(c);return d}r=Qa.prototype;r.i=function(){return this.m.value};function K(a,b){z("undefined"!==typeof b);a.m.value=b;Ra(a)}r.vb=function(){return 0<this.m.Zb};r.e=function(){return this.i()===m&&!this.vb()};
r.z=function(a){for(var b in this.m.children)a(new Qa(b,this,this.m.children[b]))};function Sa(a,b,c,d){c&&!d&&b(a);a.z(function(a){Sa(a,b,k,d)});c&&d&&b(a)}function Ta(a,b,c){for(a=c?a:a.parent();a!==m;){if(b(a))return k;a=a.parent()}return n}r.path=function(){return new H(this.fb===m?this.wb:this.fb.path()+"/"+this.wb)};r.name=aa("wb");r.parent=aa("fb");
function Ra(a){if(a.fb!==m){var b=a.fb,c=a.wb,d=a.e(),e=D(b.m.children,c);d&&e?(delete b.m.children[c],b.m.Zb--,Ra(b)):!d&&!e&&(b.m.children[c]=a.m,b.m.Zb++,Ra(b))}};function M(a,b){this.Ia=a?a:Ua;this.V=b?b:Va}function Ua(a,b){return a<b?-1:a>b?1:0}r=M.prototype;r.ea=function(a,b){return new M(this.Ia,this.V.ea(a,b,this.Ia).copy(m,m,n,m,m))};r.remove=function(a){return new M(this.Ia,this.V.remove(a,this.Ia).copy(m,m,n,m,m))};r.get=function(a){for(var b,c=this.V;!c.e();){b=this.Ia(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return m};
function Wa(a,b){for(var c,d=a.V,e=m;!d.e();){c=a.Ia(b,d.key);if(0===c){if(d.left.e())return e?e.key:m;for(d=d.left;!d.right.e();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}f("Attempted to find predecessor key for a nonexistent key.  What gives?")}r.e=function(){return this.V.e()};r.count=function(){return this.V.count()};r.$a=function(){return this.V.$a()};r.Oa=function(){return this.V.Oa()};r.pa=function(a){return this.V.pa(a)};r.Ea=function(a){return this.V.Ea(a)};
r.Ma=function(a){return new Xa(this.V,a)};function Xa(a,b){this.Mc=b;for(this.xb=[];!a.e();)this.xb.push(a),a=a.left}function Ya(a){if(0===a.xb.length)return m;var b=a.xb.pop(),c;c=a.Mc?a.Mc(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.e();)a.xb.push(b),b=b.left;return c}function Za(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=m?c:k;this.left=d!=m?d:Va;this.right=e!=m?e:Va}r=Za.prototype;
r.copy=function(a,b,c,d,e){return new Za(a!=m?a:this.key,b!=m?b:this.value,c!=m?c:this.color,d!=m?d:this.left,e!=m?e:this.right)};r.count=function(){return this.left.count()+1+this.right.count()};r.e=p(n);r.pa=function(a){return this.left.pa(a)||a(this.key,this.value)||this.right.pa(a)};r.Ea=function(a){return this.right.Ea(a)||a(this.key,this.value)||this.left.Ea(a)};function $a(a){return a.left.e()?a:$a(a.left)}r.$a=function(){return $a(this).key};
r.Oa=function(){return this.right.e()?this.key:this.right.Oa()};r.ea=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(m,m,m,e.left.ea(a,b,c),m):0===d?e.copy(m,b,m,m,m):e.copy(m,m,m,m,e.right.ea(a,b,c));return ab(e)};function bb(a){if(a.left.e())return Va;!a.left.D()&&!a.left.left.D()&&(a=cb(a));a=a.copy(m,m,m,bb(a.left),m);return ab(a)}
r.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.e()&&(!c.left.D()&&!c.left.left.D())&&(c=cb(c)),c=c.copy(m,m,m,c.left.remove(a,b),m);else{c.left.D()&&(c=db(c));!c.right.e()&&(!c.right.D()&&!c.right.left.D())&&(c=eb(c),c.left.left.D()&&(c=db(c),c=eb(c)));if(0===b(a,c.key)){if(c.right.e())return Va;d=$a(c.right);c=c.copy(d.key,d.value,m,m,bb(c.right))}c=c.copy(m,m,m,m,c.right.remove(a,b))}return ab(c)};r.D=aa("color");
function ab(a){a.right.D()&&!a.left.D()&&(a=fb(a));a.left.D()&&a.left.left.D()&&(a=db(a));a.left.D()&&a.right.D()&&(a=eb(a));return a}function cb(a){a=eb(a);a.right.left.D()&&(a=a.copy(m,m,m,m,db(a.right)),a=fb(a),a=eb(a));return a}function fb(a){var b;b=a.copy(m,m,k,m,a.right.left);return a.right.copy(m,m,a.color,b,m)}function db(a){var b;b=a.copy(m,m,k,a.left.right,m);return a.left.copy(m,m,a.color,m,b)}
function eb(a){var b,c;b=a.left.copy(m,m,!a.left.color,m,m);c=a.right.copy(m,m,!a.right.color,m,m);return a.copy(m,m,!a.color,b,c)}function gb(){}r=gb.prototype;r.copy=function(){return this};r.ea=function(a,b){return new Za(a,b,i,i,i)};r.remove=function(){return this};r.get=p(m);r.count=p(0);r.e=p(k);r.pa=p(n);r.Ea=p(n);r.$a=p(m);r.Oa=p(m);r.D=p(n);var Va=new gb;var hb=Array.prototype,ib=hb.forEach?function(a,b,c){hb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,g=0;g<d;g++)g in e&&b.call(c,e[g],g,a)},jb=hb.map?function(a,b,c){return hb.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),g=t(a)?a.split(""):a,h=0;h<d;h++)h in g&&(e[h]=b.call(c,g[h],h,a));return e};function kb(){};function lb(){this.w=[];this.Yb=[];this.Xc=[];this.Eb=[];this.Eb[0]=128;for(var a=1;64>a;++a)this.Eb[a]=0;this.reset()}ja(lb,kb);lb.prototype.reset=function(){this.w[0]=1732584193;this.w[1]=4023233417;this.w[2]=2562383102;this.w[3]=271733878;this.w[4]=3285377520;this.pc=this.Wa=0};
function mb(a,b){var c;c||(c=0);for(var d=a.Xc,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var g=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(g<<1|g>>>31)&4294967295}c=a.w[0];for(var h=a.w[1],j=a.w[2],l=a.w[3],o=a.w[4],q,e=0;80>e;e++)40>e?20>e?(g=l^h&(j^l),q=1518500249):(g=h^j^l,q=1859775393):60>e?(g=h&j|l&(h|j),q=2400959708):(g=h^j^l,q=3395469782),g=(c<<5|c>>>27)+g+o+q+d[e]&4294967295,o=l,l=j,j=(h<<30|h>>>2)&4294967295,h=c,c=g;a.w[0]=a.w[0]+c&4294967295;a.w[1]=a.w[1]+h&
4294967295;a.w[2]=a.w[2]+j&4294967295;a.w[3]=a.w[3]+l&4294967295;a.w[4]=a.w[4]+o&4294967295}lb.prototype.update=function(a,b){s(b)||(b=a.length);var c=this.Yb,d=this.Wa,e=0;if(t(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(mb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(mb(this,c),d=0);this.Wa=d;this.pc+=b};function nb(){this.Ha={};this.length=0}nb.prototype.setItem=function(a,b){D(this.Ha,a)||(this.length+=1);this.Ha[a]=b};nb.prototype.getItem=function(a){return D(this.Ha,a)?this.Ha[a]:m};nb.prototype.removeItem=function(a){D(this.Ha,a)&&(this.length-=1,delete this.Ha[a])};var N=m;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),N=sessionStorage}catch(ob){N=new nb}else N=new nb;function pb(a,b,c,d){this.host=a;this.Ob=b;this.ab=c;this.Y=d||N.getItem(a)||this.host}function qb(a,b){b!==a.Y&&(a.Y=b,"s-"===a.Y.substr(0,2)&&N.setItem(a.host,a.Y))};var rb,sb,tb,ub;function vb(){return ba.navigator?ba.navigator.userAgent:m}ub=tb=sb=rb=n;var wb;if(wb=vb()){var xb=ba.navigator;rb=0==wb.indexOf("Opera");sb=!rb&&-1!=wb.indexOf("MSIE");tb=!rb&&-1!=wb.indexOf("WebKit");ub=!rb&&!tb&&"Gecko"==xb.product}var yb=sb,zb=ub,Ab=tb;var Bb;if(rb&&ba.opera){var Cb=ba.opera.version;"function"==typeof Cb&&Cb()}else zb?Bb=/rv\:([^\);]+)(\)|;)/:yb?Bb=/MSIE\s+([^\);]+)(\)|;)/:Ab&&(Bb=/WebKit\/(\S+)/),Bb&&Bb.exec(vb());var Db=m,Eb=m;
function Fb(a,b){ea(a)||f(Error("encodeByteArray takes an array as a parameter"));if(!Db){Db={};Eb={};for(var c=0;65>c;c++)Db[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Eb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Eb:Db,d=[],e=0;e<a.length;e+=3){var g=a[e],h=e+1<a.length,j=h?a[e+1]:0,l=e+2<a.length,o=l?a[e+2]:0,q=g>>2,g=(g&3)<<4|j>>4,j=(j&15)<<2|o>>6,o=o&63;l||(o=64,h||(j=64));d.push(c[q],c[g],c[j],c[o])}return d.join("")}
;var Gb,Hb=1;Gb=function(){return Hb++};function z(a,b){a||f(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Jb(a){var b=qa(a),a=new lb;a.update(b);var b=[],c=8*a.pc;56>a.Wa?a.update(a.Eb,56-a.Wa):a.update(a.Eb,64-(a.Wa-56));for(var d=63;56<=d;d--)a.Yb[d]=c&255,c/=256;mb(a,a.Yb);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.w[d]>>e&255;return Fb(b)}
function Kb(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Kb.apply(m,arguments[b]):"object"===typeof arguments[b]?a+y(arguments[b]):a+arguments[b],a+=" ";return a}var Lb=m,Mb=k;function O(){Mb===k&&(Mb=n,Lb===m&&"true"===N.getItem("logging_enabled")&&Nb(k));if(Lb){var a=Kb.apply(m,arguments);Lb(a)}}function Ob(a){return function(){O(a,arguments)}}function Pb(){if("undefined"!==typeof console){var a=Kb.apply(m,arguments);console.log("FIREBASE INTERNAL ERROR: "+a)}}
function Qb(){var a=Kb.apply(m,arguments);f(Error("FIREBASE FATAL ERROR: "+a))}function Rb(){if("undefined"!==typeof console){var a=Kb.apply(m,arguments);console.log("FIREBASE WARNING: "+a)}}function Ba(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Sb(a,b){return a!==b?a===m?-1:b===m?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Tb(a,b){if(b&&a in b)return b[a];f(Error("Missing required key ("+a+") in object: "+y(b)))}var Ub=0;
function Ja(a){if("object"!==typeof a||a===m)return y(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=y(b[d]),c+=":",c+=Ja(a[b[d]]);return c+"}"}function Vb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c}
function Wb(a){z(!Ba(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function Xb(a,b){this.la=a;z(this.la!==m,"LeafNode shouldn't be created with null value.");this.Qa="undefined"!==typeof b?b:m}r=Xb.prototype;r.I=p(k);r.j=aa("Qa");r.Wb=function(a){return new Xb(this.la,a)};r.L=function(){return P};r.C=function(a){return E(a)===m?this:P};r.P=p(m);r.B=function(a,b){return(new Q(new M,this.Qa)).B(a,b)};r.Sa=function(a,b){var c=E(a);return c===m?b:this.B(c,P.Sa(Ka(a),b))};r.e=p(n);r.yb=p(0);
r.X=function(a){return a&&this.j()!==m?{".value":this.i(),".priority":this.j()}:this.i()};r.hash=function(){var a="";this.j()!==m&&(a+="priority:"+Yb(this.j())+":");var b=typeof this.la,a=a+(b+":"),a="number"===b?a+Wb(this.la):a+this.la;return Jb(a)};r.i=aa("la");r.toString=function(){return"string"===typeof this.la?'"'+this.la+'"':this.la};function Q(a,b){this.O=a||new M;this.Qa="undefined"!==typeof b?b:m}r=Q.prototype;r.I=p(n);r.j=aa("Qa");r.Wb=function(a){return new Q(this.O,a)};r.B=function(a,b){var c=this.O.remove(a);b&&b.e()&&(b=m);b!==m&&(c=c.ea(a,b));return b&&b.j()!==m?new Zb(c,m,this.Qa):new Q(c,this.Qa)};r.Sa=function(a,b){var c=E(a);if(c===m)return b;var d=this.L(c).Sa(Ka(a),b);return this.B(c,d)};r.e=function(){return this.O.e()};r.yb=function(){return this.O.count()};var $b=/^\d+$/;r=Q.prototype;
r.X=function(a){if(this.e())return m;var b={},c=0,d=0,e=k;this.z(function(g,h){b[g]=h.X(a);c++;e&&$b.test(g)?d=Math.max(d,Number(g)):e=n});if(!a&&e&&d<2*c){var g=[],h;for(h in b)g[h]=b[h];return g}a&&this.j()!==m&&(b[".priority"]=this.j());return b};r.hash=function(){var a="";this.j()!==m&&(a+="priority:"+Yb(this.j())+":");this.z(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Jb(a)};r.L=function(a){a=this.O.get(a);return a===m?P:a};
r.C=function(a){var b=E(a);return b===m?this:this.L(b).C(Ka(a))};r.P=function(a){return Wa(this.O,a)};r.zc=function(){return this.O.$a()};r.Bc=function(){return this.O.Oa()};r.z=function(a){return this.O.pa(a)};r.cc=function(a){return this.O.Ea(a)};r.Ma=function(){return this.O.Ma()};r.toString=function(){var a="{",b=k;this.z(function(c,d){b?b=n:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var P=new Q(new M);function Zb(a,b,c){Q.call(this,a,c);b===m&&(b=new M(ac),a.pa(function(a,c){b=b.ea({name:a,sa:c.j()},c)}));this.ha=b}ja(Zb,Q);r=Zb.prototype;r.B=function(a,b){var c=this.L(a),d=this.O,e=this.ha;c!==m&&(d=d.remove(a),e=e.remove({name:a,sa:c.j()}));b&&b.e()&&(b=m);b!==m&&(d=d.ea(a,b),e=e.ea({name:a,sa:b.j()},b));return new Zb(d,e,this.j())};r.P=function(a,b){var c=Wa(this.ha,{name:a,sa:b.j()});return c?c.name:m};r.z=function(a){return this.ha.pa(function(b,c){return a(b.name,c)})};
r.cc=function(a){return this.ha.Ea(function(b,c){return a(b.name,c)})};r.Ma=function(){return this.ha.Ma(function(a,b){return{key:a.name,value:b}})};r.zc=function(){return this.ha.e()?m:this.ha.$a().name};r.Bc=function(){return this.ha.e()?m:this.ha.Oa().name};function R(a,b){if("object"!==typeof a)return new Xb(a,b);if(a===m)return P;var c=m;".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);z(c===m||"string"===typeof c||"number"===typeof c);if(".value"in a&&a[".value"]!==m)return new Xb(a[".value"],c);var c=new Q(new M,c),d;for(d in a)if(D(a,d)&&"."!==d.substring(0,1)){var e=R(a[d]);if(e.I()||!e.e())c=c.B(d,e)}return c}function ac(a,b){return Sb(a.sa,b.sa)||(a.name!==b.name?a.name<b.name?-1:1:0)}
function Yb(a){return"number"===typeof a?"number:"+Wb(a):"string:"+a};function S(a,b){this.m=a;this.Lb=b}S.prototype.X=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.m.X()};S.prototype.val=S.prototype.X;S.prototype.$c=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.m.X(k)};S.prototype.exportVal=S.prototype.$c;S.prototype.A=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Fa("Firebase.DataSnapshot.child",a);var b=new H(a),c=this.Lb.A(b);return new S(this.m.C(b),c)};
S.prototype.child=S.prototype.A;S.prototype.dc=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Fa("Firebase.DataSnapshot.hasChild",a);var b=new H(a);return!this.m.C(b).e()};S.prototype.hasChild=S.prototype.dc;S.prototype.j=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.m.j()};S.prototype.getPriority=S.prototype.j;
S.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);C("Firebase.DataSnapshot.forEach",1,a,n);if(this.m.I())return n;var b=this;return this.m.z(function(c,d){return a(new S(d,b.Lb.A(c)))})};S.prototype.forEach=S.prototype.forEach;S.prototype.vb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.m.I()?n:!this.m.e()};S.prototype.hasChildren=S.prototype.vb;
S.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Lb.name()};S.prototype.name=S.prototype.name;S.prototype.yb=function(){A("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.m.yb()};S.prototype.numChildren=S.prototype.yb;S.prototype.kd=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Lb};S.prototype.ref=S.prototype.kd;function bc(a){this.jc=a;this.Gb=[];this.Ka=0;this.$b=-1;this.Aa=m};var cc=m;"undefined"!==typeof MozWebSocket?cc=MozWebSocket:"undefined"!==typeof WebSocket&&(cc=WebSocket);function dc(a,b,c){this.ac=a;this.c=Ob(this.ac);this.frames=this.Ya=m;this.oc=0;this.Ja=(b.Ob?"wss://":"ws://")+b.Y+"/.ws?v=5";b.host!==b.Y&&(this.Ja=this.Ja+"&ns="+b.ab);c&&(this.Ja=this.Ja+"&s="+c)}var ec;
dc.prototype.open=function(a,b){this.ra=b;this.Cb=a;this.c("websocket connecting to "+this.Ja);this.Q=new cc(this.Ja);this.Ua=n;var c=this;this.Q.onopen=function(){c.c("Websocket connected.");c.Ua=k};this.Q.onclose=function(){c.c("Websocket connection was disconnected.");c.Q=m;c.Ba()};this.Q.onmessage=function(a){if(c.Q!==m)if(a=a.data,c.frames!==m)fc(c,a);else{a:{z(c.frames===m,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.oc=b;c.frames=[];a=m;break a}}c.oc=1;
c.frames=[]}a!==m&&fc(c,a)}};this.Q.onerror=function(){c.c("WebSocket error.  Closing connection.");c.Ba()}};dc.prototype.start=function(){};dc.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&cc!==m&&!ec};function fc(a,b){a.frames.push(b);if(a.frames.length==a.oc){var c=a.frames.join("");a.frames=m;c="undefined"!==typeof JSON&&s(JSON.parse)?JSON.parse(c):ka(c);gc(a);a.Cb(c)}}
dc.prototype.send=function(a){gc(this);a=y(a);a=Vb(a,16384);1<a.length&&this.Q.send(String(a.length));for(var b=0;b<a.length;b++)this.Q.send(a[b])};dc.prototype.ob=function(){this.ya=k;this.Ya&&(clearTimeout(this.Ya),this.Ya=m);this.Q&&(this.Q.close(),this.Q=m)};dc.prototype.Ba=function(){this.ya||(this.c("WebSocket is closing itself"),this.ob(),this.ra&&(this.ra(this.Ua),this.ra=m))};dc.prototype.close=function(){this.ya||(this.c("WebSocket is being closed"),this.ob())};
function gc(a){clearTimeout(a.Ya);a.Ya=setInterval(function(){a.Q.send("0");gc(a)},45E3)};function T(a,b){for(var c in a)b.call(i,a[c],c,a)};function hc(){this.set={}}r=hc.prototype;r.add=function(a,b){this.set[a]=b!==m?b:k};r.contains=function(a){return D(this.set,a)};r.get=function(a){return this.set[a]};r.remove=function(a){delete this.set[a]};r.e=function(){var a;a:{for(a in this.set){a=n;break a}a=k}return a};r.count=function(){var a=0,b;for(b in this.set)a++;return a};r.keys=function(){var a=[],b;for(b in this.set)D(this.set,b)&&a.push(b);return a};var ic="pLPCommand",jc="pRTLPCB";function kc(a,b,c){this.ac=a;this.c=Ob(a);this.ud=b;this.Pb=c;this.Ua=n;this.rb=function(a){b.host!==b.Y&&(a.ns=b.ab);var c=[],g;for(g in a)a.hasOwnProperty(g)&&c.push(g+"="+a[g]);return(b.Ob?"https://":"http://")+b.Y+"/.lp?"+c.join("&")}}var lc;
kc.prototype.open=function(a,b){function c(){if(!d.ya){d.$=new mc(function(a,b,c){d.$&&((d.wa&&(clearTimeout(d.wa),d.wa=m),d.Ua=k,"start"==a)?(d.id=b,d.Kc=c):"close"===a?b?(d.$.Pc=n,a=d.Fc,a.$b=b,a.Aa=function(){d.Ba()},a.$b<a.Ka&&(a.Aa(),a.Aa=m)):d.Ba():f(Error("Unrecognized command received: "+a)))},function(a,b){var c=d.Fc;for(c.Gb[a]=b;c.Gb[c.Ka];){var e=c.Gb[c.Ka];delete c.Gb[c.Ka];for(var g=0;g<e.length;++g)e[g]&&c.jc(e[g]);if(c.Ka===c.$b){c.Aa&&(clearTimeout(c.Aa),c.Aa(),c.Aa=m);break}c.Ka++}},
function(){d.Ba()},d.rb);var a={start:"t"};a.ser=Math.floor(1E8*Math.random());d.$.Ub&&(a.cb=d.$.Ub);a.v="5";d.Pb&&(a.s=d.Pb);a=d.rb(a);d.c("Connecting via long-poll to "+a);nc(d.$,a,function(){})}}this.tc=0;this.T=b;this.Fc=new bc(a);this.ya=n;var d=this;this.wa=setTimeout(function(){d.c("Timed out trying to connect.");d.Ba();d.wa=m},3E4);if("complete"===document.readyState)c();else{var e=n,g=function(){document.body?e||(e=k,c()):setTimeout(g,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",
g,n),window.addEventListener("load",g,n)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&g()},n),window.attachEvent("onload",g,n))}};kc.prototype.start=function(){var a=this.$,b=this.Kc;a.ed=this.id;a.fd=b;for(a.Xb=k;oc(a););a=this.id;b=this.Kc;this.Pa=document.createElement("iframe");var c={dframe:"t"};c.id=a;c.pw=b;a=this.rb(c);this.Pa.src=a;this.Pa.style.display="none";document.body.appendChild(this.Pa)};
kc.isAvailable=function(){return lc||k};kc.prototype.ob=function(){this.ya=k;this.$&&(this.$.close(),this.$=m);this.Pa&&(document.body.removeChild(this.Pa),this.Pa=m);this.wa&&(clearTimeout(this.wa),this.wa=m)};kc.prototype.Ba=function(){this.ya||(this.c("Longpoll is closing itself"),this.ob(),this.T&&(this.T(this.Ua),this.T=m))};kc.prototype.close=function(){this.ya||(this.c("Longpoll is being closed."),this.ob())};
kc.prototype.send=function(a){for(var a=y(a),a=qa(a),a=Fb(a,k),a=Vb(a,1840),b=0;b<a.length;b++){var c=this.$;c.ib.push({pd:this.tc,td:a.length,uc:a[b]});c.Xb&&oc(c);this.tc++}};
function mc(a,b,c,d){this.rb=d;this.ra=c;this.kc=new hc;this.ib=[];this.bc=Math.floor(1E8*Math.random());this.Pc=k;this.Ub=Gb();window[ic+this.Ub]=a;window[jc+this.Ub]=b;a=document.createElement("iframe");a.style.display="none";document.body?document.body.appendChild(a):f("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");a.contentDocument?a.na=a.contentDocument:a.contentWindow?a.na=a.contentWindow.document:a.document&&(a.na=a.document);this.fa=a;
try{this.fa.na.open(),this.fa.na.write("<html><body></body></html>"),this.fa.na.close()}catch(e){O("frame writing exception"),e.stack&&O(e.stack),O(e)}}mc.prototype.close=function(){this.Xb=n;this.fa&&(this.fa.na.body.innerHTML="",document.body.removeChild(this.fa),this.fa=m);var a=this.ra;a&&(this.ra=m,a())};
function oc(a){if(a.Xb&&a.Pc&&a.kc.count()<(0<a.ib.length?2:1)){a.bc++;var b={};b.id=a.ed;b.pw=a.fd;b.ser=a.bc;for(var b=a.rb(b),c="",d=0;0<a.ib.length;)if(1870>=a.ib[0].uc.length+30+c.length){var e=a.ib.shift(),c=c+"&seg"+d+"="+e.pd+"&ts"+d+"="+e.td+"&d"+d+"="+e.uc;d++}else break;var b=b+c,g=a.bc;a.kc.add(g);var h=function(){a.kc.remove(g);oc(a)},j=setTimeout(h,25E3);nc(a,b,function(){clearTimeout(j);h()});return k}return n}
function nc(a,b,c){setTimeout(function(){try{var d=a.fa.na.createElement("script");d.type="text/javascript";d.async=k;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=m,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){O("Long-poll script failed to load.");a.close()};a.fa.na.body.appendChild(d)}catch(e){}},1)};function pc(){function a(a,c){c&&c.isAvailable()&&b.push(c)}var b=[],c=qc;if("array"==da(c))for(var d=0;d<c.length;++d)a(0,c[d]);else T(c,a);this.Tb=b}var qc=[kc,{isAvailable:p(n)},dc];function U(a,b,c,d,e,g){this.id=a;this.c=Ob("c:"+this.id+":");this.jc=c;this.bb=d;this.T=e;this.ic=g;this.K=b;this.Fb=[];this.sc=0;this.qc=new pc;this.ja=0;this.c("Connection created");rc(this)}function rc(a){var b;var c=a.qc;0<c.Tb.length?b=c.Tb[0]:f(Error("No transports available"));a.H=new b("c:"+a.id+":"+a.sc++,a.K);b=sc(a,a.H);c=tc(a,a.H);a.pb=a.H;a.mb=a.H;a.H.open(b,c);a.o=m}
function tc(a,b){return function(c){b===a.H?(a.H=m,!c&&0===a.ja?(a.c("Realtime connection failed."),"s-"===a.K.Y.substr(0,2)&&(N.removeItem(a.K.ab),a.K.Y=a.K.host)):1===a.ja&&a.c("Realtime connection lost."),a.close()):b===a.o?(c=a.o,a.o=m,(a.pb===c||a.mb===c)&&a.close()):a.c("closing an old connection")}}
function sc(a,b){return function(c){if(2!=a.ja)if(b===a.mb){var d=Tb("t",c),c=Tb("d",c);if("c"==d){if(d=Tb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,g=c.h;a.Pb=c.s;qb(a.K,g);if(0==a.ja&&(a.H.start(),c=a.H,a.c("Realtime connection established."),a.H=c,a.ja=1,a.bb&&(a.bb(d),a.bb=m),"4"!==e&&Rb("Protocol version mismatch detected"),c=1<a.qc.Tb.length?a.qc.Tb[1]:m))a.o=new c("c:"+a.id+":"+a.sc++,a.K,a.Pb),a.o.open(sc(a,a.o),tc(a,a.o))}else if("n"===d){a.c("recvd end transmission on primary");
a.mb=a.o;for(c=0;c<a.Fb.length;++c)a.Ab(a.Fb[c]);a.Fb=[];uc(a)}else"s"===d?(a.c("Connection shutdown command received. Shutting down..."),a.ic&&(a.ic(c),a.ic=m),a.T=m,a.close()):"r"===d?(a.c("Reset packet received.  New host: "+c),qb(a.K,c),1===a.ja?a.close():(vc(a),rc(a))):Pb("Unknown control packet command: "+d)}else"d"==d&&a.Ab(c)}else b===a.o?(d=Tb("t",c),c=Tb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.o.start(),a.c("sending client ack on secondary"),a.o.send({t:"c",d:{t:"a",d:{}}}),a.c("Ending transmission on primary"),
a.H.send({t:"c",d:{t:"n",d:{}}}),a.pb=a.o,uc(a)):"r"===c&&(a.c("Got a reset on secondary, closing it"),a.o.close(),(a.pb===a.o||a.mb===a.o)&&a.close())):"d"==d?a.Fb.push(c):f(Error("Unknown protocol layer: "+d))):a.c("message on old connection")}}U.prototype.mc=function(a){a={t:"d",d:a};1!==this.ja&&f("Connection is not connected");this.pb.send(a)};function uc(a){a.pb===a.o&&a.mb===a.o&&(a.c("cleaning up and promoting a connection: "+a.o.ac),a.H=a.o,a.o=m)}U.prototype.Ab=function(a){this.jc(a)};
U.prototype.close=function(){2!==this.ja&&(this.c("Closing realtime connection."),this.ja=2,vc(this),this.T&&(this.T(),this.T=m))};function vc(a){a.c("Shutting down all connections");a.H&&(a.H.close(),a.H=m);a.o&&(a.o.close(),a.o=m)};function wc(a,b,c,d){this.id=xc++;this.c=Ob("p:"+this.id+":");this.nb=k;this.Z={};this.M=[];this.eb=0;this.hc={};this.da=n;this.Kb=1E3;this.Bb=b;this.Hc=c;this.T=d;this.K=a;this.lc=m;this.Hb=[];this.ta={};this.od=0;this.Za=this.Ec=m;setTimeout(v(this.vc,this),0)}var xc=0,yc=0;r=wc.prototype;
r.Ga=function(a,b,c,d){var e=++this.od,a={r:e,a:a,b:b};this.c(y(a));this.da?this.kb.mc(a):this.Hb.push(a);var g=this,a=setTimeout(function(){var a=g.ta[e];a&&(delete g.ta[e],a.ca&&a.ca.Db&&a.ca.Db())},45E3);this.ta[e]={ca:{Cb:c,Db:d},Rc:a}};function zc(a,b,c,d,e){a.c("Listen on "+b+" for "+c);var g={p:b},d=jb(d,function(a){return Ia(a)});"{}"!==c&&(g.q=d);a.Ga("l",g,function(d){a.c("listen response",d);d=d.s;"ok"!==d&&Ac(a,b,c);e&&e(d)},function(){a.c("timed out on listen...")})}
r.Ta=function(a,b){this.tb={Yc:a,xc:n,aa:b};this.c("Authenticating using credential: "+this.tb);Bc(this)};r.qb=function(){delete this.tb;this.da&&this.Ga("unauth",{},function(){},function(){})};function Bc(a){var b=a.tb;a.da&&b&&a.Ga("auth",{cred:b.Yc},function(c){(c="ok"==c.s)||delete a.tb;b.xc||(b.xc=k,b.aa&&b.aa(c))},function(){a.c("timed out on auth...")})}
r.Tc=function(a,b,c){a=a.toString();if(Ac(this,a,b)&&this.da){this.c("Unlisten on "+a+" for "+b);var d=this,a={p:a},c=jb(c,function(a){return Ia(a)});"{}"!==b&&(a.q=c);this.Ga("u",a,m,function(){d.c("timed out on unlisten...")})}};r.ra=function(a,b){this.hc[a]=b;this.da&&Cc(this,a,b)};function Cc(a,b,c){b={p:b,d:c};a.c("onDisconnect",b);a.Ga("o",b,function(a){"ok"!==a.s&&f("onDisconnect failed: "+y(a.d))},function(){a.c("timed out on onDisconnect...")})}r.put=function(a,b,c,d){Dc(this,"p",a,b,c,d)};
function Dc(a,b,c,d,e,g){c={p:c,d:d};s(g)&&(c.h=g);a.M.push({action:b,Lc:c,F:e});a.eb++;b=a.M.length-1;a.da&&Ec(a,b)}function Ec(a,b){var c=a.M[b].action,d=a.M[b].F;a.Ga(c,a.M[b].Lc,function(e){a.c(c+" response",e);delete a.M[b];a.eb--;0===a.eb&&(a.M=[]);d&&d(e.s)},function(){a.c("timed out on put...")})}
r.Ab=function(a){if("r"in a){this.c("from server: "+y(a));var b=a.r,c=this.ta[b];c&&(delete this.ta[b],clearTimeout(c.Rc),c.ca&&c.ca.Cb&&c.ca.Cb(a.b))}else"error"in a&&f("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,c=a.b,this.c("handleServerMessage",b,c),"d"===b?this.Bb(c.p,c.d):"m"===b?this.Bb(c.p,c.d,k):"c"===b?(a=c.p,b=(b=c.q)?jb(b,function(a){return Ja(a)}).join("$"):"{}",(a=Ac(this,a,b))&&a.F&&a.F("permission_denied")):"sd"===b?this.lc?this.lc(c):"msg"in c&&"undefined"!==typeof console&&
console.log("FIREBASE: "+c.msg.replace("\n","\nFIREBASE: ")):Pb("Unrecognized action received from server: "+y(b)+"\nAre you using the latest client?"))};
r.bb=function(a){this.c("connection ready");this.da=k;this.Za=(new Date).getTime();Ub=a-(new Date).getTime();for(a=0;a<this.Hb.length;a++)this.kb.mc(this.Hb[a]);this.Hb=[];Bc(this);for(var b in this.Z)for(var c in this.Z[b])a=this.Z[b][c],zc(this,b,c,a.Ra,a.F);for(b in this.hc)Cc(this,b,this.hc[b]);for(b=0;b<this.M.length;b++)this.M[b]&&Ec(this,b);this.Hc&&this.Hc()};
r.Ic=function(){this.da=n;this.c("data client disconnected");if(!this.nb){for(var a=0;a<this.M.length;a++){var b=this.M[a];b&&"h"in b.Lc&&(b.F&&b.F("disconnect"),delete this.M[a],this.eb--)}0===this.eb&&(this.M=[]);for(var c in this.ta)a=this.ta[c],delete this.ta[c],a!==m&&(a.ca&&a.ca.Db&&a.ca.Db(),clearTimeout(a.Rc))}var d=v(function(){this.vc()},this);this.nb?(this.Za&&(3E4<(new Date).getTime()-this.Za&&(this.Kb=1E3),this.Za=m),c=Math.max(0,this.Kb-((new Date).getTime()-this.Ec)),c*=Math.random(),
this.c("Trying to reconnect in "+c+"ms"),setTimeout(d,c),this.Kb=Math.min(3E4,1.3*this.Kb)):this.Nc=function(){setTimeout(d,0)};this.T&&this.T()};r.vc=function(){if(this.nb){this.c("Making a connection attempt");this.Ec=(new Date).getTime();this.Za=m;var a=v(this.Ab,this),b=v(this.bb,this),c=v(this.Ic,this),d=this.id+":"+yc++;this.kb=new U(d,this.K,a,b,c,function(a){f(Error(a))})}};r.Na=function(){this.nb=n;this.kb?this.kb.close():this.Ic()};r.lb=function(){this.nb=k;this.Nc();this.Nc=i};
function Ac(a,b,c){b=(new H(b)).toString();c||(c="{}");var d=a.Z[b][c];delete a.Z[b][c];return d};function Fc(){this.Fa=P}function V(a,b){return a.Fa.C(b)}function W(a,b,c){a.Fa=a.Fa.Sa(b,c)}Fc.prototype.toString=function(){return this.Fa.toString()};function Gc(){this.ua=new Fc;this.J=new Fc;this.va=new Fc;this.hb=new Qa}function Hc(a,b){for(var c=V(a.ua,b),d=V(a.J,b),e=J(a.hb,b),g=n,h=e;h!==m;){if(h.i()!==m){g=k;break}h=h.parent()}if(g)return n;c=Ic(c,d,e);return c!==d?(W(a.J,b,c),k):n}function Ic(a,b,c){if(c.e())return a;if(c.i()!==m)return b;a=a||P;c.z(function(d){var d=d.name(),e=a.L(d),g=b.L(d),h=J(c,d),e=Ic(e,g,h);a=a.B(d,e)});return a}
Gc.prototype.set=function(a,b){var c=this,d=[];ib(b,function(a){var b=a.path,a=a.za,h=Gb();K(J(c.hb,b),h);W(c.J,b,a);d.push({path:b,qd:h})});return d};function Jc(a,b){ib(b,function(b){var d=b.qd,b=J(a.hb,b.path),e=b.i();z(e!==m,"pendingPut should not be null.");e===d&&K(b,m)})};function Kc(){this.xa=[]}function Lc(a,b){if(0!==b.length){a.xa.push.apply(a.xa,b);for(var c=0;c<a.xa.length;c++)if(a.xa[c]){var d=a.xa[c];a.xa[c]=m;var e=d.aa;e(d.Qc,d.jb)}a.xa=[]}};function X(a,b,c,d){this.type=a;this.ga=b;this.R=c;this.jb=d};function Mc(a){this.G=a;this.ba=[];this.wc=new Kc}function Nc(a,b,c,d,e){a.ba.push({type:b,aa:c,cancel:d,S:e});var d=[],g=Oc(a.f);a.Xa&&g.push(new X("value",a.f));for(var h=0;h<g.length;h++)if(g[h].type===b){var j=new Y(a.G.n,a.G.path);g[h].R&&(j=j.A(g[h].R));d.push({aa:e?v(c,e):c,Qc:new S(g[h].ga,j),jb:g[h].jb})}Lc(a.wc,d)}Mc.prototype.Ib=function(a,b){b=this.Jb(a,b);b!=m&&Pc(this,b)};
function Pc(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],g=e.type,h=new Y(a.G.n,a.G.path);b[d].R&&(h=h.A(b[d].R));h=new S(b[d].ga,h);"value"===e.type&&!h.vb()?g+="("+h.X()+")":"value"!==e.type&&(g+=" "+h.name());O(a.G.n.u.id+": event:"+a.G.path+":"+a.G.Ca()+":"+g);for(g=0;g<a.ba.length;g++){var j=a.ba[g];b[d].type===j.type&&c.push({aa:j.S?v(j.aa,j.S):j.aa,Qc:h,jb:e.jb})}}Lc(a.wc,c)}function Oc(a){var b=[];if(!a.I()){var c=m;a.z(function(a,e){b.push(new X("child_added",e,a,c));c=a})}return b}
function Qc(a){a.Xa||(a.Xa=k,Pc(a,[new X("value",a.f)]))};function Tc(a,b){Mc.call(this,a);this.f=b}ja(Tc,Mc);Tc.prototype.Jb=function(a,b){this.f=a;this.Xa&&b!=m&&b.push(new X("value",this.f));return b};Tc.prototype.Va=function(){return{}};function Uc(a,b){this.ub=a;this.gc=b}
function Vc(a,b,c,d,e){var g=a.C(c),h=b.C(c),d=new Uc(d,e),e=Wc(d,c,g,h),j=n;if(!g.e()&&!h.e()&&g.j()!==h.j())var j=a.C(c.parent()),l=b.C(c.parent()),o=Na(c),j=j.P(o,g)!=l.P(o,h);if(e||j){g=c;c=e;for(h=j;g.parent()!==m;){var q=a.C(g),e=b.C(g),j=g.parent();if(!d.ub||J(d.ub,j).i())l=b.C(j),o=[],g=Na(g),q.e()?(q=l.P(g,e),o.push(new X("child_added",e,g,q))):e.e()?o.push(new X("child_removed",q,g)):(q=l.P(g,e),h&&o.push(new X("child_moved",e,g,q)),c&&o.push(new X("child_changed",e,g,q))),d.gc(j,l,o);h&&
(h=n,c=k);g=j}}}function Wc(a,b,c,d){var e,g=[];c===d?e=n:c.I()&&d.I()?e=c.i()!==d.i():c.I()?(Xc(a,b,P,d,g),e=k):d.I()?(Xc(a,b,c,P,g),e=k):e=Xc(a,b,c,d,g);e?a.gc(b,d,g):c.j()!==d.j()&&a.gc(b,d,m);return e}
function Xc(a,b,c,d,e){var g=n,h=!a.ub||!J(a.ub,b).e(),j=[],l=[],o=[],q=[],x={},u={},w,L,I,G;w=c.Ma();I=Ya(w);L=d.Ma();for(G=Ya(L);I!==m||G!==m;){c=I===m?1:G===m?-1:I.key===G.key?0:ac({name:I.key,sa:I.value.j()},{name:G.key,sa:G.value.j()});if(0>c)g=ta(x,I.key),s(g)?(o.push({yc:I,Sc:j[g]}),j[g]=m):(u[I.key]=l.length,l.push(I)),g=k,I=Ya(w);else{if(0<c)g=ta(u,G.key),s(g)?(o.push({yc:l[g],Sc:G}),l[g]=m):(x[G.key]=j.length,j.push(G)),g=k;else{c=b.A(G.key);if(c=Wc(a,c,I.value,G.value))q.push(G),g=k;I=
Ya(w)}G=Ya(L)}if(!h&&g)return k}for(h=0;h<l.length;h++)if(x=l[h])c=b.A(x.key),Wc(a,c,x.value,P),e.push(new X("child_removed",x.value,x.key));for(h=0;h<j.length;h++)if(x=j[h])c=b.A(x.key),l=d.P(x.key,x.value),Wc(a,c,P,x.value),e.push(new X("child_added",x.value,x.key,l));for(h=0;h<o.length;h++)x=o[h].yc,j=o[h].Sc,c=b.A(j.key),l=d.P(j.key,j.value),e.push(new X("child_moved",j.value,j.key,l)),(c=Wc(a,c,x.value,j.value))&&q.push(j);for(h=0;h<q.length;h++)a=q[h],l=d.P(a.key,a.value),e.push(new X("child_changed",
a.value,a.key,l));return g};function Yc(){this.gb=this.ka=m;this.set={}}ja(Yc,hc);r=Yc.prototype;r.setActive=function(a){this.ka=a};function Zc(a){return a.contains("default")}function $c(a){return a.ka!=m&&Zc(a)}r.defaultView=function(){return Zc(this)?this.get("default"):m};r.path=aa("gb");r.toString=function(){return jb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};r.Ra=function(){var a=[];T(this.set,function(b){a.push(b.G)});return a};function ad(a,b){Mc.call(this,a);this.f=P;this.Jb(b,Oc(b))}ja(ad,Mc);
ad.prototype.Jb=function(a,b){if(b===m)return b;var c=[],d=this.G;s(d.W)&&(s(d.ia)&&d.ia!=m?c.push(function(a,b){var c=Sb(b,d.W);return 0<c||0===c&&a>=d.ia}):c.push(function(a,b){return 0<=Sb(b,d.W)}));s(d.oa)&&(s(d.La)?c.push(function(a,b){var c=Sb(b,d.oa);return 0>c||0===c&&a<=d.La}):c.push(function(a,b){return 0>=Sb(b,d.oa)}));var e=m,g=m;if(s(this.G.qa))if(s(this.G.W)){if(e=bd(a,c,this.G.qa,n)){var h=a.L(e).j();c.push(function(a,b){var c=Sb(b,h);return 0>c||0===c&&a<=e})}}else if(g=bd(a,c,this.G.qa,
k)){var j=a.L(g).j();c.push(function(a,b){var c=Sb(b,j);return 0<c||0===c&&a>=g})}for(var l=[],o=[],q=[],x=[],u=0;u<b.length;u++){var w=b[u].R,L=b[u].ga;switch(b[u].type){case "child_added":cd(c,w,L)&&(this.f=this.f.B(w,L),o.push(b[u]));break;case "child_removed":this.f.L(w).e()||(this.f=this.f.B(w,m),l.push(b[u]));break;case "child_changed":!this.f.L(w).e()&&cd(c,w,L)&&(this.f=this.f.B(w,L),x.push(b[u]));break;case "child_moved":var I=!this.f.L(w).e(),G=cd(c,w,L);I?G?(this.f=this.f.B(w,L),q.push(b[u])):
(l.push(new X("child_removed",this.f.L(w),w)),this.f=this.f.B(w,m)):G&&(this.f=this.f.B(w,L),o.push(b[u]))}}var Rc=e||g;if(Rc){var Sc=(u=g!==m)?this.f.zc():this.f.Bc(),Ib=n,La=n,Ma=this;(u?a.cc:a.z).call(a,function(a,b){!La&&Sc===m&&(La=k);if(La&&Ib)return k;Ib?(l.push(new X("child_removed",Ma.f.L(a),a)),Ma.f=Ma.f.B(a,m)):La&&(o.push(new X("child_added",b,a)),Ma.f=Ma.f.B(a,b));Sc===a&&(La=k);a===Rc&&(Ib=k)})}for(u=0;u<o.length;u++)c=o[u],w=this.f.P(c.R,c.ga),l.push(new X("child_added",c.ga,c.R,w));
for(u=0;u<q.length;u++)c=q[u],w=this.f.P(c.R,c.ga),l.push(new X("child_moved",c.ga,c.R,w));for(u=0;u<x.length;u++)c=x[u],w=this.f.P(c.R,c.ga),l.push(new X("child_changed",c.ga,c.R,w));this.Xa&&0<l.length&&l.push(new X("value",this.f));return l};function bd(a,b,c,d){if(a.I())return m;var e=m;(d?a.cc:a.z).call(a,function(a,d){if(cd(b,a,d)&&(e=a,c--,0===c))return k});return e}function cd(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.j()))return n;return k}
ad.prototype.dc=function(a){return this.f.L(a)!==P};ad.prototype.Va=function(a,b,c){var d={};this.f.I()||this.f.z(function(a){d[a]=k});var e=this.f,c=V(c,new H("")),g=new Qa;K(J(g,this.G.path),k);var h=P.Sa(a,b),j=[];Vc(c,h,a,g,function(a,b,c){c!==m&&(j=j.concat(c))});this.Jb(b,j);this.f.I()||this.f.z(function(a){d[a]=k});this.f=e;return d};function dd(a,b){this.u=a;this.g=b;this.Gc=b.Fa;this.ma=new Qa}
dd.prototype.sb=function(a,b,c,d,e){var g=a.path,h=J(this.ma,g),j=h.i();j===m?(j=new Yc,K(h,j)):z(!j.e(),"We shouldn't be storing empty QueryMaps");var l=a.Ca();if(j.contains(l))Nc(j.get(l),b,c,d,e);else{var o=this.g.Fa.C(g),a="default"===a.Ca()?new Tc(a,o):new ad(a,o);if($c(j)||ed(h))j.add(l,a),j.gb||(j.gb=a.G.path);else{var q,x;j.e()||(q=j.toString(),x=j.Ra());j.add(l,a);j.gb||(j.gb=a.G.path);j.setActive(fd(this,j));q&&x&&this.u.Tc(j.path(),q,x)}$c(j)&&Sa(h,function(a){if(a=a.i()){a.ka&&a.ka();
a.ka=m}});Nc(a,b,c,d,e);(b=(b=Ta(J(this.ma,g),function(a){var b;if(b=a.i())if(b=a.i().defaultView())b=a.i().defaultView().Xa;if(b)return k},k))||this.u===m)&&Qc(a)}};function gd(a,b,c,d,e){for(var g=a.get(b),h=n,j=g.ba.length-1;0<=j;j--){var l=g.ba[j];if((!c||l.type===c)&&(!d||l.aa===d)&&(!e||l.S===e))if(g.ba.splice(j,1),h=k,c&&d)break}(c=h&&!(0<g.ba.length))&&a.remove(b);return c}dd.prototype.Mb=function(a,b,c,d){var e=J(this.ma,a.path).i();return e===m?m:hd(this,e,a,b,c,d)};
function hd(a,b,c,d,e,g){var h=b.path(),h=J(a.ma,h),c=c?c.Ca():m,j=[];c&&"default"!==c?gd(b,c,d,e,g)&&j.push(c):ib(b.keys(),function(a){gd(b,a,d,e,g)&&j.push(a)});b.e()&&K(h,m);c=ed(h);if(0<j.length&&!c){for(var l=h,o=h.parent(),c=n;!c&&o;){var q=o.i();if(q){z(!$c(q));var x=l.name(),u=n;T(q.set,function(a){u=a.dc(x)||u});u&&(c=k)}l=o;o=o.parent()}l=m;if(!$c(b)){o=b.ka;b.ka=m;var w=[],L=function(b){var c=b.i();c&&Zc(c)?(w.push(c.path()),c.ka==m&&c.setActive(fd(a,c))):(c&&c.ka==m&&c.setActive(fd(a,
c)),b.z(L))};L(h);l=w;o&&o()}return c?m:l}return m}function id(a,b,c){Sa(J(a.ma,b),function(a){(a=a.i())&&T(a.set,function(a){Qc(a)})},c,k)}function jd(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return k;return n}var e=a.Gc,g=a.g.Fa;a.Gc=g;var h=b.toString();Vc(e,g,b,a.ma,function(b,c,e){if(b.toString().substring(0,h.length)===h){var g=d(b);g&&id(a,b,n);a.Ib(b,c,e);g&&id(a,b,k)}else a.Ib(b,c,e)});d(b)&&id(a,b,k)}
dd.prototype.Ib=function(a,b,c){a=J(this.ma,a).i();a!==m&&T(a.set,function(a){a.Ib(b,c)})};function ed(a){return Ta(a,function(a){return a.i()&&$c(a.i())})}
function fd(a,b){if(a.u){var c=b.keys(),d=a.u,e=function(d){"ok"!==d?(Rb("on() or once() for "+b.path().toString()+" failed: "+d),b&&T(b.set,function(a){for(var b=0;b<a.ba.length;b++){var c=a.ba[b];c.cancel&&(c.S?v(c.cancel,c.S):c.cancel)()}}),hd(a,b)):ib(c,function(a){(a=b.get(a))&&Qc(a)})},g=b.toString(),h=b.path().toString();d.Z[h]=d.Z[h]||{};z(!d.Z[h][g],"listen() called twice for same path/queryId.");d.Z[h][g]={Ra:b.Ra(),F:e};d.da&&zc(d,h,g,b.Ra(),e);return v(a.u.Tc,a.u,b.path(),b.toString(),
b.Ra())}return ca}dd.prototype.Va=function(a,b,c,d){var e={};T(b.set,function(b){b=b.Va(a,c,d);T(b,function(a,b){e[b]=D(e,b)?e:a})});c.I()||c.z(function(a){D(e,a)||(e[a]=n)});return e};
function kd(a,b,c,d,e,g){var h=b.path();if(g!==m){var j=[];d.I()||d.z(function(a,b){j.push({path:h.A(a),za:b});delete g[a]});T(g,function(a,b){j.push({path:h.A(b),za:P})});return j}var b=a.Va(h,b,d,e),l=P,o=[];T(b,function(b,g){var h=new H(g);b?l=l.B(g,d.C(h)):o=o.concat(ld(a,d.C(h),J(c,h),e))});return[{path:h,za:l}].concat(o)}
function md(a,b,c,d,e){for(var g=J(a.ma,b),h=g.parent(),j=n;!j&&h!==m;){var l=h.i();l!==m&&(Zc(l)?j=k:(l=a.Va(b,l,c,d),g=g.name(),ta(l,g)&&(j=k)));g=h;h=h.parent()}if(j)return[{path:b,za:c}];h=J(a.ma,b);j=h.i();return j!==m?Zc(j)?[{path:b,za:c}]:kd(a,j,h,c,d,e):ld(a,c,h,d)}function ld(a,b,c,d){var e=c.i();if(e!==m)return Zc(e)?[{path:c.path(),za:b}]:kd(a,e,c,b,d,m);if(b.I())return[];var g=[];b.z(function(b,e){var l=new H(b);g=g.concat(ld(a,e,J(c,l),d))});return g};function nd(a){this.K=a;this.u=new wc(this.K,v(this.Bb,this),v(this.gd,this),v(this.hd,this));this.Sb=new Qa;this.g=new Gc;this.N=new dd(this.u,this.g.va);this.Cc=new Fc;this.ec=new dd(m,this.Cc);od(this,n)}r=nd.prototype;r.toString=function(){return(this.K.Ob?"https://":"http://")+this.K.host};r.name=function(){return this.K.ab};
r.Bb=function(a,b,c){var d=[],e=m;if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new H(a.substring(0,a.length-9)),c=V(this.g.ua,a).Wb(b),d.push(a);else if(c){var e=b,a=new H(a),c=V(this.g.ua,a),g;for(g in b){var h=R(b[g]),c=c.B(g,h);d.push(a.A(g))}}else a=new H(a),c=R(b),d.push(a);b=md(this.N,a,c,this.g.J,e);e=n;for(g=0;g<b.length;++g){var c=b[g],h=this.g,j=c.path;W(h.ua,j,c.za);e=Hc(h,j)||e}e&&(a=pd(this,a),qd(this,a),a=a.path());jd(this.N,a,d)};r.gd=function(){od(this,k)};
r.hd=function(){od(this,n)};function od(a,b){var c=new H("/.info/connected");W(a.Cc,c,R(b));jd(a.ec,c,[c])}r.Ta=function(a,b){this.u.Ta(a,b)};r.qb=function(){this.u.qb()};
r.Rb=function(a,b,c,d){this.c("set",{path:a.toString(),value:b});var b=R(b,c),c=md(this.N,a,b,this.g.J,m),e=this.g.set(a,c),g=this;this.u.put(a.toString(),b.X(k),function(b){var c="ok"===b;Jc(g.g,e);c||(Rb("set at "+a+" failed: "+b),Hc(g.g,a),b=pd(g,a),qd(g,b),jd(g.N,b.path(),[]));d&&d(c)});b=pd(this,a);rd(this,a);qd(this,b);jd(this.N,b.path(),[a])};
r.update=function(a,b,c){this.c("update",{path:a.toString(),value:b});var d=V(this.g.va,a),e=k,g=[],h;for(h in b){var e=n,j=R(b[h]),d=d.B(h,j);g.push(a.A(h))}if(e)O("update() called with empty data.  Don't do anything."),c&&c(k);else{var d=md(this.N,a,d,this.g.J,b),l=this.g.set(a,d),o=this;Dc(this.u,"m",a.toString(),b,function(b){z("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");b="ok"===b;Jc(o.g,l);c&&c(b)},i);b=pd(this,a);rd(this,a);qd(this,b);jd(this.N,b.path(),g)}};
r.nc=function(a,b,c){this.c("setPriority",{path:a.toString(),sa:b});var d=V(this.g.J,a).Wb(b),d=md(this.N,a,d,this.g.J,m),e=this.g.set(a,d),g=this;this.u.put(a.toString()+"/.priority",b,function(a){a="ok"===a;Jc(g.g,e);c&&c(a)});a=pd(this,a);qd(this,a);jd(this.N,a.path(),[])};r.Qb=function(a,b){this.u.ra(a.toString(),b)};r.sb=function(a,b,c,d,e){".info"===E(a.path)?this.ec.sb(a,b,c,d,e):this.N.sb(a,b,c,d,e)};
r.Mb=function(a,b,c,d){if(".info"===E(a.path))this.ec.Mb(a,b,c,d);else if(b=this.N.Mb(a,b,c,d),b!==m){for(var c=this.g,a=a.path,d=[],e=0;e<b.length;++e)d[e]=V(c.ua,b[e]);W(c.ua,a,P);for(e=0;e<b.length;++e)W(c.ua,b[e],d[e])}};r.Na=function(){this.u.Na()};r.lb=function(){this.u.lb()};r.c=function(){O("r:"+this.u.id+":",arguments)};function sd(a,b){var c=new Y(a,b);return new S(V(a.g.va,b),c)};function rd(a,b){var c=J(a.Sb,b);Ta(c,function(b){td(a,b)});td(a,c);Sa(c,function(b){td(a,b)})}function td(a,b){var c=b.i();if(c!==m){for(var d=-1,e=[],g=0;g<c.length;g++)if(2===c[g].status)z(d===g-1,"All SENT items should be at beginning of queue."),d=g,c[g].status=4,c[g].rc="set";else if(c[g].Vb(),c[g].F){var h=sd(a,b.path());e.push(v(c[g].F,m,n,h))}-1===d?K(b,m):c.length=d+1;for(g=0;g<e.length;g++)e[g]()}}
function ud(a,b){var c=b||a.Sb;b||vd(a,c);if(!c.e())if(c.i()!==m){var d=wd(a,c);if(0!==d.length){var e=c.path();if(2!==d[0].status&&4!==d[0].status){for(var g=0;g<d.length;g++)z(1===d[g].status,"tryToSendTransactionForNode_: items in queue should all be run."),d[g].status=2,d[g].Oc++;var h=V(a.g.J,e).hash();W(a.g.J,e,V(a.g.va,e));var j=V(a.g.J,e).X(k),l=Gb();K(J(a.g.hb,e),l);a.u.put(e.toString(),j,function(b){a.c("transaction put response",{path:e.toString(),status:b});var h=J(a.g.hb,e),j=h.i();z(j!==
m,"tryToSendTransactionsForNode_: pendingPut should not be null.");j===l&&(K(h,m),W(a.g.J,e,V(a.g.ua,e)));if("ok"===b){b=[];for(g=0;g<d.length;g++)d[g].status=3,d[g].F&&(h=sd(a,d[g].path),b.push(v(d[g].F,m,k,h))),d[g].Vb();vd(a,c);ud(a);for(g=0;g<b.length;g++)b[g]()}else{if("datastale"===b)for(g=0;g<d.length;g++)d[g].status=4===d[g].status?5:1;else{Rb("transaction at "+e+" failed: "+b);for(g=0;g<d.length;g++)d[g].status=5,d[g].rc=b}b=pd(a,e);qd(a,b);jd(a.N,b.path(),[e])}},h)}}}else c.z(function(b){ud(a,
b)})}
function qd(a,b){var c=b.path();W(a.g.va,c,V(a.g.J,c));var d=wd(a,b);if(0!==d.length){for(var e=V(a.g.va,c),g=[],h=0;h<d.length;h++){var j=Oa(c,d[h].path),l=n,o;z(j!==m,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===d[h].status)l=k,o=d[h].rc;else if(1===d[h].status)if(25<=d[h].Oc)l=k,o="maxretry";else{var q=d[h].update(e.C(j).X());s(q)?(za("transaction failed: Data returned ",q),e=e.Sa(j,R(q))):(l=k,o="nodata")}l&&(d[h].Vb(),d[h].status=3,d[h].F&&(l=new Y(a,d[h].path),j=new S(e.C(j),
l),g.push(v(d[h].F,m,n,j,o))))}d=V(a.g.J,c).j();W(a.g.va,c,e.Wb(d));ud(a);for(h=0;h<g.length;h++)g[h]()}}function pd(a,b){for(var c,d=a.Sb;(c=E(b))!==m&&d.i()===m;)d=J(d,c),b=Ka(b);return d}function wd(a,b){var c=[];xd(a,b,c);c.sort(function(a,b){return a.Jc-b.Jc});return c}function xd(a,b,c){var d=b.i();if(d!==m)for(var e=0;e<d.length;e++)c.push(d[e]);b.z(function(b){xd(a,b,c)})}
function vd(a,b){var c=b.i();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;K(b,0<c.length?c:m)}b.z(function(b){vd(a,b)})};function Z(){this.Da={}}Z.Ac=function(){return Z.Dc?Z.Dc:Z.Dc=new Z};Z.prototype.Na=function(){for(var a in this.Da)this.Da[a].Na()};Z.prototype.interrupt=Z.prototype.Na;Z.prototype.lb=function(){for(var a in this.Da)this.Da[a].lb()};Z.prototype.resume=Z.prototype.lb;var $={nd:function(){return Z.Ac().Da}};$.repos=$.nd;$.bd=function(a){var b=Q.prototype.hash;Q.prototype.hash=a;return function(){Q.prototype.hash=b}};$.hijackHash=$.bd;$.Ca=function(a){return a.Ca()};$.queryIdentifier=$.Ca;$.dd=function(a){return a.n.u.Z};$.listens=$.dd;$.ld=function(a){return a.n.u.kb};$.refConnection=$.ld;$.Vc=wc;$.DataConnection=$.Vc;wc.prototype.sendRequest=wc.prototype.Ga;wc.prototype.interrupt=wc.prototype.Na;$.Wc=U;$.RealTimeConnection=$.Wc;U.prototype.sendRequest=U.prototype.mc;
U.prototype.close=U.prototype.close;$.Uc=pb;$.ConnectionTarget=$.Uc;$.ad=function(){lc=ec=k};$.forceLongPolling=$.ad;$.rd=function(a,b){a.n.u.lc=b};$.setSecurityDebugCallback=$.rd;var yd,zd=0,Ad=[];yd=function(){var a=(new Date).getTime()+Ub,b=a===zd;zd=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);z(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Ad[d];d--)Ad[d]=0;Ad[d]++}else for(d=0;12>d;d++)Ad[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Ad[d]);z(20===a.length,"NextPushId: Length should be 20.");return a};function Y(){var a,b,c;if(arguments[0]instanceof nd)c=arguments[0],a=arguments[1];else{A("new Firebase",1,2,arguments.length);var d=arguments[0],e="";a="";b=k;var g="";if(t(d)){e=d.indexOf("//");0<=e&&(b="http:"!==d.substring(0,e),d=d.substring(e+2));var h=d.indexOf("/");-1===h&&(h=d.length);e=d.substring(0,h);d=d.substring(h+1);h=e.split(".");if(3==h.length){if("firebase"===h[1])Qb(e+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");else{a=h[0];g="";d=("/"+d).split("/");
for(h=0;h<d.length;h++)if(0<d[h].length){var j=d[h];try{j=decodeURIComponent(j.replace(/\+/g," "))}catch(l){}g+="/"+j}}a=a.toLowerCase()}else a=m}b||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&Rb("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new pb(e,b,a);b=new H(g);e=b.toString();if(!(d=!t(a.host)))if(!(d=0===a.host.length))if(!(d=!xa(a.ab)))if(d=0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,
"/")),d=!(t(e)&&0!==e.length&&!wa.test(e));d&&f(Error(B("new Firebase",1,n)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Z?c=arguments[1]:f(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Z.Ac();e=(a.Ob?"https://":"http://")+a.host;d=ta(c.Da,e);d||(d=new nd(a),c.Da[e]=d);c=d;a=b}F.call(this,c,a)}ja(Y,F);var Bd=Y,Cd=["Firebase"],Dd=ba;
!(Cd[0]in Dd)&&Dd.execScript&&Dd.execScript("var "+Cd[0]);for(var Ed;Cd.length&&(Ed=Cd.shift());)!Cd.length&&s(Bd)?Dd[Ed]=Bd:Dd=Dd[Ed]?Dd[Ed]:Dd[Ed]={};Y.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.e()?m:Na(this.path)};Y.prototype.name=Y.prototype.name;
Y.prototype.A=function(a){A("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof H))if(E(this.path)===m){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Fa("Firebase.child",b)}else Fa("Firebase.child",a);return new Y(this.n,this.path.A(a))};Y.prototype.child=Y.prototype.A;Y.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===m?m:new Y(this.n,a)};Y.prototype.parent=Y.prototype.parent;
Y.prototype.toString=function(){A("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===m)a=this.n.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};Y.prototype.toString=Y.prototype.toString;Y.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);Ga("Firebase.set",this.path);ya("Firebase.set",a,n);C("Firebase.set",2,b,k);return this.n.Rb(this.path,a,m,b)};Y.prototype.set=Y.prototype.set;
Y.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);Ga("Firebase.update",this.path);ga(a)||f(Error(B("Firebase.update",1,n)+" must be an object containing the children to replace."));ya("Firebase.update",a,n);C("Firebase.update",2,b,k);return this.n.update(this.path,a,b)};Y.prototype.update=Y.prototype.update;
Y.prototype.Rb=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);Ga("Firebase.setWithPriority",this.path);ya("Firebase.setWithPriority",a,n);Ca("Firebase.setWithPriority",2,b,n);C("Firebase.setWithPriority",3,c,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.n.Rb(this.path,a,b,c)};Y.prototype.setWithPriority=Y.prototype.Rb;
Y.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);Ga("Firebase.remove",this.path);C("Firebase.remove",1,a,k);this.set(m,a)};Y.prototype.remove=Y.prototype.remove;
Y.prototype.transaction=function(a,b){function c(){}A("Firebase.transaction",1,2,arguments.length);Ga("Firebase.transaction",this.path);C("Firebase.transaction",1,a,n);C("Firebase.transaction",2,b,k);(".length"===this.name()||".keys"===this.name())&&f("Firebase.transaction failed: "+this.name()+" is a read-only object.");var d=this.n,e=this.path;d.c("transaction on "+e);var g=new Y(d,e);g.fc("value",c);var h={path:e,update:a,F:b,Jc:Gb(),Oc:0,Vb:function(){g.zb("value",c)}},j=d.g.va,l=h.update(V(j,
e).X());if(s(l)){za("transaction failed: Data returned ",l);var o=V(d.g.J,e).j();W(j,e,R(l,o));jd(d.N,e,[e]);h.status=1;e=J(d.Sb,e);j=e.i()||[];j.push(h);K(e,j);ud(d)}else h.Vb(),h.F&&(d=sd(d,e),h.F(n,d))};Y.prototype.transaction=Y.prototype.transaction;Y.prototype.nc=function(a,b){A("Firebase.setPriority",1,2,arguments.length);Ga("Firebase.setPriority",this.path);Ca("Firebase.setPriority",1,a,n);C("Firebase.setPriority",2,b,k);this.n.nc(this.path,a,b)};Y.prototype.setPriority=Y.prototype.nc;
Y.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);Ga("Firebase.push",this.path);ya("Firebase.push",a,k);C("Firebase.push",2,b,k);var c=yd(),c=this.A(c);"undefined"!==typeof a&&a!==m&&c.set(a,b);return c};Y.prototype.push=Y.prototype.push;Y.prototype.md=function(){A("Firebase.removeOnDisconnect",0,0,arguments.length);this.n.Qb(this.path,m)};Y.prototype.removeOnDisconnect=Y.prototype.md;
Y.prototype.Qb=function(a){A("Firebase.setOnDisconnect",1,1,arguments.length);ya("Firebase.setOnDisconnect",a,n);this.n.Qb(this.path,a)};Y.prototype.setOnDisconnect=Y.prototype.Qb;Y.prototype.Ta=function(a,b){A("Firebase.auth",1,2,arguments.length);t(a)||f(Error(B("Firebase.auth",1,n)+"must be a valid credential (a string)."));C("Firebase.auth",2,b,k);this.n.Ta(a,b)};Y.prototype.auth=Y.prototype.Ta;Y.prototype.qb=function(){this.n.qb()};Y.prototype.unauth=Y.prototype.qb;
function Nb(a,b){z(!b||a===k||a===n,"Can't turn on custom loggers persistently.");a===k?("undefined"!==typeof console&&("function"===typeof console.log?Lb=v(console.log,console):"object"===typeof console.log&&(Lb=function(a){console.log(a)})),b&&N.setItem("logging_enabled","true")):a?Lb=a:(Lb=m,N.removeItem("logging_enabled"))}Y.enableLogging=Nb;Y.TEST_HOOKS=$;Y.Context=Z;})();
